services:

  backend:
    build: ./backend
    container_name: ninjadatabridge_backend
    restart: always

  nginx:
    build: ./frontend
    container_name: ninjadatabridge_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    restart: always